# Generated by Django 4.1.6 on 2023-02-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=' ', upload_to='profile', verbose_name='Personal Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Examination price :'),
        ),
    ]
