# Generated by Django 4.1.6 on 2023-02-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_join_us_profile_type_of_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('Dermatologist', 'Dermatologist'), ('dentist', 'dentist'), ('psychiatrist', 'psychiatrist'), ('newborn pediatrician', 'newborn pediatrician'), ('neurologist', 'neurologist'), ('orthopedist', 'orthopedist'), ('obstetrician-gynecologist', 'obstetrician-gynecologist'), ('ear, nose and throat doctor', 'ear, nose and throat doctor'), ('cardiologist and vascular doctor', 'cardiologist and vascular doctor'), ('hematologist', 'hematologist'), ('oncologist', 'oncologist'), ('internal doctor', 'internal doctor'), ('Dietitian and Nutritionist', 'Dietitian and Nutritionist'), ('pediatric surgeon', 'pediatric surgeon'), ('surgical oncologist', 'surgical oncologist'), ('vascular surgeon', 'vascular surgeon'), ('Plastic Surgeon Doctor', 'Plastic Surgeon Doctor'), ('Obesity and Laparoscopic Surgeon', 'Obesity and Laparoscopic Surgeon')], max_length=80, null=True, verbose_name='doctor ?'),
        ),
    ]
